# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      IF ( $([String]Vmaction) -eq "Startup" ) {
                Start-AzVM -ResourceGroupName $(resourcegroupname) -Name $(vmname)
            }
            IF ( $([String]Vmaction) -eq "shutdown" ) {
                Stop-AzVM -ResourceGroupName $(resourcegroupname) -Name $(vmname)-Force
            }