# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  window

- Steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure for Students (865bcc00-2a24-4188-b8c4-2d968f54d241)-6546'
    ScriptType: 'InlineScript'
    Inline: |
      -EnvironmentName: "AzureCloud",
       -homeTenantId: "2580f19d-0c06-493f-a534-a5987bfa9c05",
       -id: "865bcc00-2a24-4188-b8c4-2d968f54d241",
      Start-AzureRMVM -Name Vm -ResourceGroupName azvirtualmachine
    azurePowerShellVersion: 'LatestVersion'



