# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure for Students (865bcc00-2a24-4188-b8c4-2d968f54d241)'
    ScriptType: 'InlineScript'
    Inline: 'Start-AzVM  -Name "vm" -ResourceGroupName "azvirtualmachine"'
    azurePowerShellVersion: 'LatestVersion'