# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

- Steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'Azure for Students (865bcc00-2a24-4188-b8c4-2d968f54d241)-6546'
      ScriptType: 'InlineScript'
      Inline: |
      Start-AzureRMVM -Name Vm -ResourceGroupName azvirtualmachine
      azurePowerShellVersion: 'LatestVersion'



