# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      param([string]$VmName,[string]$ResourceGroupName,[ValidateSet("startup", "shutdown")],[string]$VmAction)
      IF ($VmAction -eq "Startup") {
          Start-AzureRMVM -Name $VmName -ResourceGroupName $ResourceGroupName
      }
      IF ($VmAction -eq "shutdown") {
          Stop-AzureRMVM -Name $VmName -ResourceGroupName $ResourceGroupName -Force
      }
  