# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      IF (${env:VMACTION} -eq "Startup") {
          Start-AzVM -Name ${env:VMNAME} -ResourceGroupName ${env:RESOURCEGROUPNAME}
      }
      IF (${env:VMACTION} -eq "shutdown") {
          Stop-AzVM -Name ${env:VMNAME} -ResourceGroupName ${env:RESOURCEGROUPNAME} -Force
      }
  